spring.application.name=chronos

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/chronos}
spring.datasource.username=${DATABASE_USERNAME:chronos}
spring.datasource.password=${DATABASE_PASSWORD:chronos}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
