global:
  scrape_interval: 5s

scrape_configs:
  - job_name: chronos-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [chronos-api:8080]

  - job_name: chronos-worker
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [chronos-worker:8080]