apiVersion: v1
kind: ConfigMap
metadata:
  name: chronos-config
  namespace: chronos
data:
  CHRONOS_MODE: all
  CHRONOS_WORKER_CONCURRENCY: "4"
  CHRONOS_OUTBOX_PUBLISHER_INTERVAL_MS: "1000"
  CHRONOS_SCHEDULER_INTERVAL_MS: "1000"
  CHRONOS_WORKER_LEASE_RECOVERY_INTERVAL_MS: "10000"
  CHRONOS_RETRY_BASE_DELAY_MS: "2000"
  CHRONOS_RETRY_MAX_DELAY_MS: "30000"
