apiVersion: v1
kind: Secret
metadata:
  name: chronos-infrastructure
  namespace: chronos
type: Opaque
stringData:
  DATABASE_URL: jdbc:postgresql://postgres:5432/chronos
  DATABASE_USERNAME: chronos
  DATABASE_PASSWORD: replace-for-cluster
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: chronos
  RABBITMQ_PASSWORD: replace-for-cluster
  KEDA_RABBITMQ_HOST: amqp://chronos:replace-for-cluster@rabbitmq:5672/
